# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew tap generator
class Rktool < Formula
  desc "A test tool for Homebrew tap"
  homepage "https://github.com/lvzh2012/homebrew-tool"
  version "1.0.0"
  license "MIT"

  # 从 GitHub 仓库下载文件
  url "https://raw.githubusercontent.com/lvzh2012/homebrew-tool/main/rktool.sh"
  sha256 "59c811cedd8c3902d6b804cd7304b01421215b949878c4a95609fba5a78be3ad"

  def install
    # 将脚本安装到 bin 目录，并重命名为 rktool
    # bin.install 会自动设置执行权限，但我们需要确保源文件也有执行权限
    bin.install "rktool.sh" => "rktool"
    # 显式设置执行权限（确保）
    system "chmod", "+x", bin/"rktool"
  end

  test do
    # 测试脚本是否正常工作
    assert_match "version", shell_output("#{bin}/rktool -v")
  end
end
