# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew tap generator
class Rktool < Formula
  desc "A test tool for Homebrew tap"
  homepage "https://github.com/lvzh2012/homebrew-tool"
  version "1.0.0"
  license "MIT"

  # 使用 tap 目录中的文件
  # 文件应该位于 Formula 文件同一目录下
  url "file://#{File.expand_path(__dir__)}/rktool.sh"
  sha256 "b23f5dae46bf1ba6323b6f35a21dfe486e98a24b40168afea275a33819d1f280"

  def install
    # 将脚本安装到 bin 目录，并重命名为 rktool
    # bin.install 会自动设置执行权限，但我们需要确保源文件也有执行权限
    bin.install "rktool.sh" => "rktool"
    # 显式设置执行权限（确保）
    system "chmod", "+x", bin/"rktool"
    
    # 同时安装 spinner.sh 作为库文件，方便其他脚本使用
    libexec.install "spinner.sh"
    system "chmod", "+x", libexec/"spinner.sh"
  end

  test do
    # 测试脚本是否正常工作
    assert_match "version", shell_output("#{bin}/rktool -v")
  end
end
