# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew tap generator
class Rktool < Formula
  desc "Install Libarclite files into Xcode toolchain (e.g. arc for Swift/ObjC)"
  homepage "https://github.com/lvzh2012/homebrew-tool"
  version "1.0.1"
  license "MIT"

  # 从 GitHub 仓库下载文件
  url "https://raw.githubusercontent.com/lvzh2012/homebrew-tool/main/rktool.sh"
  sha256 "34a85c4e7c86c18185707801c0ce56c95e92c2457269580d283d4a9d5b1241bf"

  def install
    # 将脚本安装到 bin 目录，并重命名为 rktool
    # bin.install 会自动设置执行权限，但我们需要确保源文件也有执行权限
    bin.install "rktool.sh" => "rktool"
    # 显式设置执行权限（确保）
    system "chmod", "+x", bin/"rktool"
  end

  test do
    # 测试脚本是否正常工作
    assert_match "version", shell_output("#{bin}/rktool -v")
  end
end
