# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew tap generator
class Spinner < Formula
  desc "Universal shell script animation library with spinner, dots, and progress bar animations"
  homepage "https://github.com/lvzh2012/homebrew-tool"
  version "1.0.0"
  license "MIT"

  # 从 GitHub 仓库下载文件
  url "https://raw.githubusercontent.com/lvzh2012/homebrew-tool/main/spinner.sh"
  sha256 "dc0ad195dfba9b15060f4f8f5f48f7ee65c1b3fd5979e09d6175a84b3b68ee23"

  def install
    # 将脚本安装到 libexec 目录（库文件通常放在这里）
    libexec.install "spinner.sh"
    # 创建一个包装脚本，方便用户使用
    bin.install_symlink libexec/"spinner.sh" => "spinner"
    # 显式设置执行权限
    system "chmod", "+x", libexec/"spinner.sh"
  end

  def caveats
    <<~EOS
      spinner.sh 已安装到 #{libexec}/spinner.sh

      使用方法：
      1. 在脚本中引入：
         source #{libexec}/spinner.sh

      2. 使用动画函数：
         spinner "正在处理..." "your_command"
         dots "正在处理..." "your_command"
         progress_bar "正在处理..." "your_command"

      或者直接使用：
        spinner "提示信息" "命令"
    EOS
  end

  test do
    # 测试脚本是否可以正常 source
    assert_match "spinner", shell_output("source #{libexec}/spinner.sh && type spinner")
  end
end

