# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew tap generator
class TestTool < Formula
  desc "A test tool for Homebrew tap"
  homepage "https://github.com/yourusername/tool"
  version "1.0.0"
  license "MIT"

  # 使用本地文件路径
  # 注意：对于本地 tap，使用 file:// URL
  # 如果推送到 Git 仓库，可以改为 Git URL
  url "file://#{File.expand_path(__dir__)}/../test.py"
  sha256 "2fc164b8756de059f16a79bfd19a915de45189bf0063be176c83f463817972d7"

  def install
    # 将脚本安装到 bin 目录，并重命名为 test-tool
    bin.install "test.py" => "test-tool"
    # 确保脚本有执行权限
    chmod 0755, bin/"test-tool"
  end

  test do
    # 测试脚本是否正常工作
    assert_match "Welcome", shell_output("#{bin}/test-tool")
  end
end

