# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew tap generator
class TestTool < Formula
  desc "A test tool for Homebrew tap"
  homepage "https://github.com/yourusername/tool"
  version "1.0.0"
  license "MIT"

  # 使用 tap 目录中的文件
  # 文件应该位于 Formula 文件同一目录下
  url "file://#{File.expand_path(__dir__)}/test.py"
  sha256 "bd12cfb53cc7c7bb8881f3625a93695c75ff65f4b65caed7f30c66055c737728"

  def install
    # 将脚本安装到 bin 目录，并重命名为 test-tool
    bin.install "test.py" => "test-tool"
    # 确保脚本有执行权限
    chmod 0755, bin/"test-tool"
  end

  test do
    # 测试脚本是否正常工作
    assert_match "Welcome", shell_output("#{bin}/test-tool")
  end
end

